services:
  main-db:
    build:
      dockerfile: DatabaseFiles/tournament-main/Dockerfile
    container_name: tournament-db-main
    environment:
     MYSQL_ROOT_PASSWORD: RootPassword
     MYSQL_USER: MainUser
     MYSQL_HOST: localhost
     MYSQL_PASSWORD: MainPassword
     MYSQL_DATABASE: Tournament
    ports:
      - "5500:3306"
  name-db:
    build:
      dockerfile: DatabaseFiles/name/Dockerfile
    container_name: tournament-db-name
    environment:
     MYSQL_ROOT_PASSWORD: RootPassword
     MYSQL_USER: MainUser
     MYSQL_HOST: localhost
     MYSQL_PASSWORD: MainPassword
     MYSQL_DATABASE: TournamentName
    ports:
      - "5501:3306"
  test-db:
    build:
      dockerfile: DatabaseFiles/tournament-test/Dockerfile
    container_name: tournament-db-test
    environment:
     MYSQL_ROOT_PASSWORD: RootPassword
     MYSQL_USER: MainUser
     MYSQL_HOST: localhost
     MYSQL_PASSWORD: MainPassword
     MYSQL_DATABASE: TournamentTest
    ports:
      - "5502:3306"
  analysis-db:
    build:
      dockerfile: DatabaseFiles/tournament-analysis/Dockerfile
    container_name: tournament-db-analysis
    environment:
     MYSQL_ROOT_PASSWORD: RootPassword
     MYSQL_USER: MainUser
     MYSQL_HOST: localhost
     MYSQL_PASSWORD: MainPassword
     MYSQL_DATABASE: TournamentAnalysis
    ports:
      - "5503:3306"