from classes.club import Club 


class LogsHandler:
    """
    Class that contains static methods to handle the logs 
    generated by the BaseGame class

    ...

    Methods
    -------

    get_game_stats(logs: dict, home: Club, away: Club)
        Return a formated list of Game().logs['game_stats'] from the Game().home and Game().away
    
    prepare_game_stats_logs_to_db(logs: dict)
        Return a formated list of the Game().logs['game_stats'] 
        to be inserted in the tournament.games on Database

    prepare_game_logs_to_db(logs: dict, game_stats_id: list)
        Return a formated list to be inserted in the tournament.game_stats on Database
    
    prepare_championships_logs_to_db(logs: dict, club: int, season: int)
        Returan a formated list to be inserted in the tournament.championships on Database
    """
    
    @staticmethod
    def get_player_stats(logs: dict, stat: str) -> list:
        """Filter the players stats from logs

        Parameters
        ----------
        logs : dict
            Dict of data from from Game().logs
        stat : str
            String the stat that you want to get from logs

        Returns
        -------
            A list with player and number of the stat 
        """
        pass

    @staticmethod
    def get_game_stats(logs: dict, home: Club, away: Club) -> dict:
        """Return the game stats from logs 
        
        Parameters
        ----------
        logs : dict
            The return dict from the Game().logs
        home : Club
            The Club object that matches Game().home
        away : Club
            The Club object that matches Game().home

        Returns
        -------
            Add the clubs's ids on the logs['game_stats'] 
            and return a dict with home and away game_stats 
        """

        logs['game_stats'][home.name]['club_id'] = home.id
        logs['game_stats'][away.name]['club_id'] = away.id

        return logs['game_stats']
    
    @staticmethod
    def prepare_game_stats_logs_to_db(logs: dict) -> list[list]:
        """Convert logs dict to data to be inserted on database 
        
        Parameters
        ----------
        logs : dict
            The Game().logs['game_stats'] with club's id inserted

        Returns
        -------
            A list formated with the data to be inserted in the 
            tournament.game_stats table
        """
        
        data = []

        for _, items in logs.items():
            data.append([
                items['goals'],
                items['shots'],
                items['shots on target'],
                items['fouls'],
                items['passes'],
                items['wrong passes'],
                items['interceptions'],
                items['tackles'],
                items['stolen_balls'],
                items['saves'],
                items['ball possession'],
                items['offsides'],
                items['free kicks'],
                items['penalties'],
                items['club_id']
            ])

        return data

    @staticmethod
    def prepare_game_logs_to_db(logs: dict, game_stats_id: list) -> list:
        """Convert logs dict to data to be inserted on database 
        
        Parameters
        ----------
        logs : dict
            The return dict from Game().logs 
        game_stats_id: list
            A list containing the database game_stats.id from the home and away club
        
        Returns
        -------
            A list formated with the data to be inserted in the 
            tournamet.game table
        """
        
        conditions = logs['field']['conditions']
        
        return [
            conditions['season'],
            conditions['hour'],
            conditions['climate'],
            conditions['weather'],
            logs['field']['stadium'],
            logs['field']['audience'],
            logs['finances']['ticket_price'],
            game_stats_id[0],
            game_stats_id[1]
        ]

    @staticmethod
    def prepare_championships_logs_to_db(logs: dict, club: Club, season: str) -> list:
        """Convert and prepare the logs to insert a chmapionships table
        
        Parameters
        ----------
        logs : dict
            The return dict from Game().logs
        club : Club
            A Club Object
        season : str
            The value of the season from the championship

        Returns
        -------
            A formated list with a data to be inserted in the 
            tournament.championships table
        
            [ win, loss, draw, home_goals, away_goals, goals_diff, club_id, season ]
        """
         
        data = []

        if logs['others']['draw']:
            data += [1,0,0,1]
        elif logs['others']['winner'] == club.name:
            data += [3,1,0,0]
        else:
            data += [0,0,1,0]

        data.append(logs['others']['home_goals'])
        data.append(logs['others']['away_goals'])
        data.append(data[0] - data[1])

        data.append(club.id)
        data.append(season)

        return data